name: Release

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.releaserc'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/2.release.yml'

  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - '.releaserc'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/2.release.yml'
jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Crítico para o semantic-release analisar histórico
          ref: main # força o checkout na branch main
          # ref: ${{ github.event.workflow_run.head_sha }} # Usa o commit exato do teste

      - name: Verify merge commit
        run: |
          echo "Merge commit SHA: ${{ github.event.workflow_run.head_sha }}"
          git fetch origin main --depth=1
          git checkout ${{ github.event.workflow_run.head_sha }}
          git log -1 --pretty=fuller

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --ignore-scripts # Evita scripts pós-install desnecessários


      - name: Debug commits
        run: |
          git log --oneline -n 10
          echo "Current branch: $(git branch --show-current)"

      - name: Debug environment
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          git remote -v
          git branch -a

      # - name: Dump GitHub context
      #   run: echo "${{ toJson(github) }}"

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Opcional: só se publicar no npm
        run: npx semantic-release --debug
